baseURL = "https://anoshkin.space"
theme = "v1"

[params]
    yandexMetrikaId="52367554"
    description="personal site"
    title="Anoshkin Alexey"
    githubLink="github.com/axel-n/personal_site"

    useUnsplashBackground=true
    useFooter=true